version: '3.9'
services:

  ansible:
    image: quay.io/ansible/ansible-runner
    container_name: ansible
    network_mode: host
    volumes:
      - ./inventory:/runner/inventory
      - ./playbook:/runner/playbook
      - ./ansible.cfg:/runner/ansible.cfg
